version: '3'
services:
  laravel:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app

  vuejs:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app